# Generated by Django 4.0.1 on 2022-02-08 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_core', '0005_alter_servicetype_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_core.servicetype'),
        ),
    ]
