# Generated by Django 4.0.1 on 2022-02-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_core', '0006_event_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetime',
            name='start_time',
            field=models.TimeField(unique=True),
        ),
    ]
