# Generated by Django 4.0.1 on 2022-02-09 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_core', '0008_eventorder_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventorder',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_core.event'),
        ),
    ]
