# Generated by Django 4.0.1 on 2022-02-09 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_core', '0010_orderitem_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventorder',
            name='total_length',
        ),
    ]
