# Generated by Django 4.0.1 on 2022-02-09 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_core', '0011_remove_eventorder_total_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='length',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
    ]
