# Generated by Django 4.0.1 on 2022-02-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_core', '0014_orderitem_item_type'),
        ('apps_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ManyToManyField(blank=True, null=True, to='apps_core.Team'),
        ),
    ]
